text={  "Reggel felébredtem. Mit tegyek?":"I woke up in the morning. What should I do now?",
        "fogmosás":"Brushing my teeth",
        "reggeli":"Breakfast",
        "öltözés":"Get dressed",
        "66-os parancs":"Road 66",
        "Elmegyek fogatmosni. Sikálom rendesen, ahogy kell!":"I'm going to brush my teeth. I brush it properly, as I should!",
        "Kellene valamit enni! Anya csinált valamit? Nézzük meg!":"You should eat something! Did mom do something? Let's look at!",
        "Kissé hűvös van, Kelle valami ruha! \nFelveszek egy nadrágot, meg egy pólót!":"It's a bit chilly, I need some clothes! \nI'll put on some pants and a t-shirt!"
        "Ma koncertre megyek, elötte dönteni kéne, hogy itthon vagy egy étteremben eszek.":"Today I'm going to a concert, before that I should decide whether to eat at home or in a restaurant.",
        "Itthon ettem, most elindulok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"Itthon ettem, most elindulok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?",
        "Étteremben ettem, most elinduok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"I ate at a restaurant, now I'm going to the concert, should I buy a ticket on the way or at the venue?",
        "otthon":"home",
        "étteremben":"in the restaurant",
        "odaúton":"on the way there",
        "helyszínen":"helyszínen",
        "koncert":"koncert",
        "helyszínen veszem a jegyet, beállok a sorba.":"helyszínen veszem a jegyet, beállok a sorba.",
        "ideúton vettem a jegyet, nem kell sorban állnom.":"ideúton vettem a jegyet, nem kell sorban állnom.",
        "kártyával fizetek":"kártyával fizetek",
        "kézpénzel fizetek":"kézpénzel fizetek",
        "iszok valamit":"iszok valamit",
        "megpróbálok minél közelebb jutni a sziínpadhoz":"megpróbálok minél közelebb jutni a sziínpadhoz",
        "Fizettem, mit tegyek?":"Fizettenm mit tegyek?",
        "vodka alma":"vodka alma",
        "jager":"jager",
        "Cappy":"Cappy",
        "Mit igyak?":"Mit igyak?",
    }
